from enum import Enum

class States(Enum):
    IDLE = "IDLE"
    LOGIN_ACCOUNT = "LOGIN_ACCOUNT"
    LOGIN_PIN = "LOGIN_PIN"
    AUTHENTICATED = "AUTHENTICATED"
    TRANSFER_ACCOUNT = "TRANSFER_ACCOUNT"
    TRANSFER_AMOUNT = "TRANSFER_AMOUNT"
    TRANSFER_CONFIRM = "TRANSFER_CONFIRM"